### ISSUE TITLE
Use alt account or offline mode, preventing invalid session errors

### ISSUE THREAD

**Issue by creeper123123321** [ViaVersion/VIAaaS#7]

**Comment by Matando** [comment]
It seems your handling the minecraft java auth by having the user load a webpage in their browser. Why don't you instead just handle the auth request serverside?

Mojang could be blocking the account because the auth is coming from one ip (the javascript in the web browser page) and then being used on another ip (the VIAaaS instance/server)

This should, hopefully, prevent Mojang from blocking the accounts.

**Comment by creeper123123321** [comment]
There are some points in handling in proxy server: the user will need to send email/password, needing them to trust the proxy server. There would be more packets for handle for making a chat available for player to type.

When using it on a web browser, the user will store the access token in the browser, not neeeding to send a password nor access token to the VIAaaS server. Using a web browser, it has less Minecraft packets to handle during the login phase.
However it requires using a CORS Proxy for proxying the Mojang Auth/Session API, which may make Mojang flag as suspicious activity, as there will be "suspect" IP logged in the account. This happens too when using Geyser on a remote server, which calls Mojang API with the "suspect" IP https://github.com/GeyserMC/Geyser/wiki/Common-Issues#mojang-resetting-account-credentials . Maybe if I use a local CORS Proxy on the local machine which the address isn't suspect it won't flag as suspect.
